version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: blood_pressure
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - '3307:3306'
    expose:
      - 3307

  backend: 
    build:
      context: ../../src
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=db  
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=blood_pressure
    ports:
      - 8080:8080
