# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: blood_pressure
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - 3306:3306